language: java
branches:
  only:
    - master
    - travis
script:
  - cd WebApp/
  - gradle build
before_deploy:
  - cd build/libs/
deploy:
  provider: releases
  file: "WebApp.war"
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: C6is5iuDObowxer9PscZiz0EtvhlUzOjexURvwJwmGJGbYBDkQbpvJe7STpAat5SMau7tosAwVdxqL0S2w1m+q2chRw/OzrnlSlX95ORrvl6RHWj6igjHXajiVdhExg6NmYicMPRtHfFnLWMNn7/UqGJ1Nbf5sHQ2dL382p2I2QYytT9+Is53Fy2rrFVNOI7xSsCAH5UcOUGcQ6ZnWjAMWCq8jnaC+G2NwjK4zmk2hHikJThVjKfoDo2me3WFCyHb7JsZ9ECBtnjL73IwMlyyUNtMpwL9wcuXkmWfHJVMbKdGgssuMleIhibYNDTeWKmwgIaYxrKfd8wQx8FFwjTE2a+2NyvQfN7wjI9hJkYoHUeDr5laJnw1c4lgHFfhf1rptCpnUdMAv1RDXqQjEvVMnY4mJf+jYEsDFwiyl/YXctIUshuxY0Q/SGjrJzv+83FyoChDPccYd5mD03r18ie9f7Rq3HV/nl4sJQbYo1Yh4K4Kks3G7CZOX4O97gbDL5RmQiFEkwX93ALdgB3BXsBz+3rcK/x/HqnnoHBVqsHNsyG9cX8RYlAoRsAwBDd64vvMiVBO3roU19XHd8GNmyBNJnNrts0TNyvuNEaQPDZs5xxLn6UNJrxEVPzDIm6QNtCURSuIBAb4s5QQhT58ltU3gNzM2AZXXculM2N+N2Xl18=
  on:
    repo: lognaume/HEIGVD-AMT-Project
