CREATE DATABASE AMT;

USE AMT;

CREATE TABLE `Kebab_Shop` (
	`id` INT(11) NULL DEFAULT NULL,
	`name` VARCHAR(50) NULL DEFAULT NULL,
	`street` VARCHAR(50) NULL DEFAULT NULL,
	`city` VARCHAR(50) NULL DEFAULT NULL,
	`country` VARCHAR(50) NULL DEFAULT NULL,
	`phone` VARCHAR(50) NULL DEFAULT NULL,
	`kebab_average_price` FLOAT NULL DEFAULT NULL,
	`creation_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);